commit

diff --git a/.github/workflows/sonarqube-scanner.yml b/.github/workflows/sonarqube-scanner.yml
--- a/.github/workflows/sonarqube-scanner.yml
+++ b/.github/workflows/sonarqube-scanner.yml
@@ -83,14 +83,15 @@ jobs:
         run: cat .scannerwork/report-task.txt
 
       - name: SonarQube Quality Gate check
-        id: sonarqube-quality-gate-check
-        uses: sonarsource/sonarqube-quality-gate-action@master
-        timeout-minutes: 10
-        with:
-          scanMetadataReportFile: .scannerwork/report-task.txt
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
+        run: |
+          SONAR_PROJECT_KEY="sonarqube-test" 
+          SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}"
 
-      - name: "show SonarQube Quality Gate Status value"
-        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
+          RESULT=$(curl -s -u "${{ secrets.SONAR_TOKEN }}" "https://sonarqube.example.com/api/qualitygates/project_status?projectKey=${SONAR_PROJECT_KEY}")
+          STATUS=$(echo "$RESULT" | jq -r '.projectStatus.status')
+
+          echo "$STATUS"
+          if [ "$STATUS" != "OK" ]; then
+            echo "SonarQube Quality Gate check failed"
+            exit 1
+          fi
